# Generated by Django 4.1.3 on 2022-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_mysqldatabase_id_alter_nodescript_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodescript",
            name="name",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
