# Generated by Django 4.1.3 on 2022-11-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nodescript_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='folder',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
