# Generated by Django 4.1.3 on 2022-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_website_folder_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodescript',
            name='port',
            field=models.IntegerField(default=3002),
            preserve_default=False,
        ),
    ]
